name: toolchain

on: 
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mipsel-linux-uclibc-gcc7, mipsel-linux-musl-gcc7, mipsel-linux-uclibc-gcc8, mipsel-linux-musl-gcc8, mipsel-linux-uclibc-gcc9, mipsel-linux-musl-gcc9, mipsel-linux-uclibc-gcc10, mipsel-linux-musl-gcc10, mipsel-linux-uclibc-gcc13, mipsel-linux-musl-gcc13]
    steps:
      - uses: actions/checkout@main
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Build toolchain
        run: |
          make CT_TARGET=${CT_TARGET} CT_VERSION=${CT_VERSION}
          cd crosstool-ng-${CT_VERSION}/toolchain-mipsel
          tar cJf ../../${CT_TARGET}.tar.xz *
        env:
          CT_TARGET: ${{ matrix.target }}
          CT_VERSION: 1.26.0
        working-directory: toolchain
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: toolchain/${{ matrix.target }}.tar.xz
      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: toolchain/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true